version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: code-review-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: code-review-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: code_review
    ports:
      - "5432:5432"
  

  api-gateway:
    build: ./api-gateway
    container_name: code-review-api-gateway
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:dev123@postgres:5432/code_review
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"

  worker:
    build: ./worker
    container_name: code-review-worker
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:dev123@postgres:5432/code_review
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
